name:                ripper
version:             1.3.0
github:              githubuser/ripper
license:             MIT
author:              Author name here
maintainer:          example@example.com
copyright:           2022 Author name here

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/ripper#readme>

dependencies:
- base >= 4.11 && < 10
- rio >= 0.1.12.0

default-extensions:
- DerivingStrategies
- FlexibleContexts
- GeneralizedNewtypeDeriving
- ImportQualifiedPost
- NamedFieldPuns
- NumericUnderscores
- OverloadedStrings
- ScopedTypeVariables
- TypeApplications

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Werror=missing-methods
- -Werror=missing-fields
- -Werror=incomplete-patterns

library:
  source-dirs: src
  default-extensions:
    - NumericUnderscores
  dependencies:
    - aeson
    - attoparsec
    - bytestring
    - directory
    - exceptions
    - filepath
    - conduit
    - http-conduit
    - http-client
    - http-client-tls
    - http-types
    - monad-logger
    - mtl
    - optparse-applicative
    - process
    - shake
    - sqlite-simple
    - text
    - time
    - transformers
    - xml

executables:
  ripper-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - ripper
    - bytestring
    - http-client
    - http-client-tls
    - mtl
    - optparse-applicative
    - sqlite-simple
    - text
    - transformers

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  ripper-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - ripper
    - aeson
    - bytestring
    - directory
    - filepath
    - hspec
    - hspec-attoparsec
    - http-client
    - http-conduit
    - http-types
    - monad-logger
    - mtl
    - raw-strings-qq
    - sqlite-simple
    - text
    - time
    - transformers

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wno-missing-export-lists
