name:                rssgen
version:             0.5.1.0
github:              "githubuser/rssgen"
license:             MIT
author:              "Eugene Nikolsky <e@egeek.me>"
copyright:           "2020–2022 Eugene Nikolsky"

extra-source-files:
- README.md
- ChangeLog.md
# based on https://github.com/ulfsauer0815/ghmm/commit/e9da1940f56f7a88bea03a17b7f75c0fc397e45d
- test/data/radiot.rss

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/rssgen#readme>

dependencies:
- aeson
- base >= 4.7 && < 5
- bytestring
- mtl
- http-client
- http-client-tls
- sqlite-simple
- text
- time
- transformers

ghc-options:
- -Werror=missing-fields

library:
  source-dirs: src
  dependencies:
  - directory
  - exceptions
  - filepath
  - http-types
  - xml

executables:
  rssgen-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rssgen
    - shake

tests:
  rssgen-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - hspec-discover
    - raw-strings-qq
    - rssgen
    - time
